INCLUDEPATH += $$PWD
INCLUDEPATH += $$PWD/archives
INCLUDEPATH += $$PWD/compressors
INCLUDEPATH += $$PWD/core
INCLUDEPATH += $$PWD/diskimages
INCLUDEPATH += $$PWD/documents
INCLUDEPATH += $$PWD/filesystems
INCLUDEPATH += $$PWD/games
INCLUDEPATH += $$PWD/installers
INCLUDEPATH += $$PWD/packages
INCLUDEPATH += $$PWD/sfx
INCLUDEPATH += $$PWD/tar
INCLUDEPATH += $$PWD/transport
DEPENDPATH += $$PWD
INCLUDEPATH += $$PWD/Algos
DEPENDPATH += $$PWD/Algos
INCLUDEPATH += $$PWD/Algos/include
DEPENDPATH += $$PWD/Algos/include

# The shared core (all classes relocated to Formats, XCompress/XDecompress,
# ALL Algos decoders, and xbinary/xoptions/xpng/xjavaclass/xandroidbinary)
# lives in xzip.pri so it can be used WITHOUT the USE_ARCHIVE define; this file
# adds only the formats that remain in XArchive.
!contains(XCONFIG, xzip) {
    XCONFIG += xzip
    include($$PWD/xzip.pri)
}

include($$PWD/deark.pri)
include($$PWD/legacydisk.pri)

# The .cpp-or-.c fallback it arrived with is dropped: Algos is C++-only by a
# rule XArchive's in.sh enforces, so the .c branch is unreachable here.
NSIS_BZIP2_SOURCE = $$PWD/Algos/nsis_bzip2/nsis_bzip2.cpp
!exists($$NSIS_BZIP2_SOURCE) {
    error("Cannot find $$NSIS_BZIP2_SOURCE")
}

HEADERS += \
    $$PWD/Algos/nsis_bzip2/nsis_bzip2.h \
    $$PWD/Algos/nsis_bzip2/nsis_bzip2_private.h \
    $$PWD/tar/x_ar.h \
    $$PWD/archives/xsqlitearchive.h \
    $$PWD/archives/xcpmcompressedarchive.h \
    $$PWD/Algos/xcpmcrunchdecoder.h \
    $$PWD/archives/xgitobjectarchive.h \
    $$PWD/archives/xalzarchive.h \
    $$PWD/archives/xfreearcnative.h \
    $$PWD/Algos/xfreearcdecoder.h \
    $$PWD/archives/xrziparchive.h \
    $$PWD/documents/xchmarchive.h \
    $$PWD/filesystems/xntfsarchive.h \
    $$PWD/games/xhog2.h \
    $$PWD/games/xpboarchive.h \
    $$PWD/Algos/xrzipdecoder.h \
    $$PWD/diskimages/xvirtualdiskarchive.h \
    $$PWD/archives/xancient.h \
    $$PWD/transport/xlegacyencoded.h \
    $$PWD/archives/xdearkarchive.h \
    $$PWD/diskimages/xdskexp.h \
    $$PWD/diskimages/xlibdskarchive.h \
    $$PWD/diskimages/xadfarchive.h \
    $$PWD/archives/xcompactproarchive.h \
    $$PWD/archives/xdiskdoublerarchive.h \
    $$PWD/archives/xfls.h \
    $$PWD/archives/xpyinstallercarchive.h \
    $$PWD/installers/xwisesfxarchive.h \
    $$PWD/installers/xis3sfxarchive.h \
    $$PWD/installers/xis14sfxarchive.h \
    $$PWD/core/xlegacystorearchive.h \
    $$PWD/archives/xconcatziparchive.h \
    $$PWD/archives/xwinimageziparchive.h \
    $$PWD/diskimages/xdiskjugglerarchive.h \
    $$PWD/transport/xapplesingle.h \
    $$PWD/diskimages/x2img.h \
    $$PWD/archives/xpyz.h \
    $$PWD/archives/xlzxarchive.h \
    $$PWD/archives/xmi10archive.h \
    $$PWD/transport/xmacbinary.h \
    $$PWD/transport/xresourcefork.h \
    $$PWD/archives/xlbr.h \
    $$PWD/archives/xrtpatch.h \
    $$PWD/compressors/xrncarchive.h \
    $$PWD/archives/xlarcpfx.h \
    $$PWD/archives/xarq.h \
    $$PWD/archives/xnetwarepackedfile.h \
    $$PWD/archives/xpovlablzh.h \
    $$PWD/archives/xearefpack.h \
    $$PWD/documents/xprintshopdeluxe.h \
    $$PWD/archives/xfrontpagetheme.h \
    $$PWD/archives/xsecondnature.h \
    $$PWD/compressors/xlzpis2.h \
    $$PWD/documents/xfinereaderpack.h \
    $$PWD/archives/xecmpacked.h \
    $$PWD/games/xgstpack.h \
    $$PWD/archives/xnpack.h \
    $$PWD/archives/xcorelltec.h \
    $$PWD/archives/xirwinpac.h \
    $$PWD/archives/xdtpacked.h \
    $$PWD/compressors/xgashuff.h \
    $$PWD/archives/xpowerboardbbs.h \
    $$PWD/archives/xclayarchive.h \
    $$PWD/archives/xsclarchive.h \
    $$PWD/diskimages/xfdiimage.h \
    $$PWD/diskimages/xpcmimage.h \
    $$PWD/archives/xpowerarc.h \
    $$PWD/diskimages/xapricotimage.h \
    $$PWD/diskimages/xcisoimage.h \
    $$PWD/diskimages/xcloopimage.h \
    $$PWD/archives/xbigafarchive.h \
    $$PWD/filesystems/xromfsarchive.h \
    $$PWD/archives/xchieflzarchive.h \
    $$PWD/archives/xhaarchive.h \
    $$PWD/archives/xclparchive.h \
    $$PWD/archives/xlimarchive.h \
    $$PWD/archives/xainarchive.h \
    $$PWD/archives/xobfuscatedarchive.h \
    $$PWD/archives/xuleadarchive.h \
    $$PWD/archives/xtopspeedarchive.h \
    $$PWD/archives/xtwsarchive.h \
    $$PWD/archives/xzzarchive.h \
    $$PWD/archives/xcruarchive.h \
    $$PWD/installers/xsfxgziparchive.h \
    $$PWD/tar/xtarx2archive.h \
    $$PWD/archives/xsqxarchive.h \
    $$PWD/archives/xpakleoarchive.h \
    $$PWD/archives/xtpsarchive.h \
    $$PWD/archives/xtgcfarchive.h \
    $$PWD/archives/xzxziparchive.h \
    $$PWD/archives/ximparchive.h \
    $$PWD/archives/xsfpackarchive.h \
    $$PWD/archives/xvmarcarchive.h \
    $$PWD/archives/xtersearchive.h \
    $$PWD/diskimages/xvmdkarchive.h \
    $$PWD/filesystems/xsquashfsarchive.h \
    $$PWD/archives/xpanoramaarchive.h \
    $$PWD/packages/xvmssavesetarchive.h \
    $$PWD/archives/xziearchive.h \
    $$PWD/diskimages/xteledeskarchive.h \
    $$PWD/games/xteacyarchive.h \
    $$PWD/diskimages/xx64archive.h \
    $$PWD/archives/xchieflzmultiarchive.h \
    $$PWD/archives/xcflarchive.h \
    $$PWD/transport/xtnefarchive.h \
    $$PWD/archives/xqdaarchive.h \
    $$PWD/archives/xdpkarchive.h \
    $$PWD/archives/xdsl2archive.h \
    $$PWD/archives/xzlwbarchive.h \
    $$PWD/archives/xc64wraptorarchive.h \
    $$PWD/packages/xvmsdatabasearchive.h \
    $$PWD/tar/xtarx1archive.h \
    $$PWD/packages/xvmspcsiarchive.h \
    $$PWD/archives/xzaparchive.h \
    $$PWD/archives/xtrcpakarchive.h \
    $$PWD/archives/xzzzarchive.h \
    $$PWD/archives/xzfsfarchive.h \
    $$PWD/archives/xti99arcarchive.h \
    $$PWD/tar/xtarnextsteparchive.h \
    $$PWD/diskimages/xtrdosarchive.h \
    $$PWD/archives/xxeditpackarchive.h \
    $$PWD/archives/xzoomarchive.h \
    $$PWD/archives/xzcmparchive.h \
    $$PWD/archives/xwintersoftarchive.h \
    $$PWD/archives/xzpakarchive.h \
    $$PWD/archives/xztcarchive.h \
    $$PWD/archives/xtivoliarchive.h \
    $$PWD/archives/xwpkarchive.h \
    $$PWD/archives/xtrcarchive.h \
    $$PWD/diskimages/xcopyqmarchive.h \
    $$PWD/archives/xkboomarchive.h \
    $$PWD/archives/xbigfarchive.h \
    $$PWD/archives/xarcfs.h \
    $$PWD/archives/xcmparchive.h \
    $$PWD/packages/xbeospackage.h \
    $$PWD/games/xsilmarils.h \
    $$PWD/installers/xis7inx.h \
    $$PWD/archives/xrawlzw15v.h \
    $$PWD/archives/xlbrcobol.h \
    $$PWD/archives/xlsz.h \
    $$PWD/games/xgob.h \
    $$PWD/archives/xgtu.h \
    $$PWD/documents/xnotetab.h \
    $$PWD/installers/xizpack.h \
    $$PWD/packages/xsolarispackage.h \
    $$PWD/archives/xhlb.h \
    $$PWD/archives/xrid.h \
    $$PWD/archives/xrompaq.h \
    $$PWD/archives/xfiz.h \
    $$PWD/archives/xmiz.h \
    $$PWD/archives/xibmspack.h \
    $$PWD/archives/xea.h \
    $$PWD/archives/xsls.h \
    $$PWD/archives/xpcsecure.h \
    $$PWD/diskimages/xpmdiskcopy.h \
    $$PWD/games/xmegatechvol.h \
    $$PWD/archives/xigf1.h \
    $$PWD/archives/xjetbbs.h \
    $$PWD/installers/xmakeself.h \
    $$PWD/archives/xfld.h \
    $$PWD/archives/xglu.h \
    $$PWD/archives/xjam.h \
    $$PWD/archives/xfmc1.h \
    $$PWD/archives/xsoftpaq2.h \
    $$PWD/archives/xmarc.h \
    $$PWD/archives/xstork.h \
    $$PWD/archives/xseadata.h \
    $$PWD/archives/xqnxbase.h \
    $$PWD/archives/xgamos.h \
    $$PWD/archives/xsos.h \
    $$PWD/documents/xexesbookbuilder.h \
    $$PWD/compressors/xhuff.h \
    $$PWD/archives/xlzhcxp.h \
    $$PWD/archives/xkrml.h \
    $$PWD/archives/xqip1.h \
    $$PWD/archives/xquantum.h \
    $$PWD/archives/xirixsa.h \
    $$PWD/archives/xjm93.h \
    $$PWD/diskimages/xnextstepdiskimage.h \
    $$PWD/archives/xmva.h \
    $$PWD/archives/xpkt.h \
    $$PWD/diskimages/xhdcopy.h \
    $$PWD/archives/xivt.h \
    $$PWD/archives/xswag.h \
    $$PWD/archives/xstylus.h \
    $$PWD/games/xsettlersft.h \
    $$PWD/archives/xriversoft.h \
    $$PWD/installers/xgksetup.h \
    $$PWD/packages/xopc.h \
    $$PWD/games/xgob2.h \
    $$PWD/compressors/xsq.h \
    $$PWD/compressors/xoraclesqueeze.h \
    $$PWD/installers/xis11.h \
    $$PWD/documents/xrecognita.h \
    $$PWD/archives/xinteduft.h \
    $$PWD/documents/xpaperport.h \
    $$PWD/archives/xealib.h \
    $$PWD/archives/xnid.h \
    $$PWD/archives/xhap.h \
    $$PWD/documents/xexeebookcreator.h \
    $$PWD/compressors/xlzdiet.h \
    $$PWD/archives/xqualitas.h \
    $$PWD/compressors/xlzv1.h \
    $$PWD/compressors/xxpakarchive.h \
    $$PWD/archives/xsw.h \
    $$PWD/archives/xsaf.h \
    $$PWD/archives/xigf2.h \
    $$PWD/archives/xrcf.h \
    $$PWD/diskimages/xhfe.h \
    $$PWD/archives/xrsvk.h \
    $$PWD/archives/xhzl.h \
    $$PWD/archives/xjbf.h \
    $$PWD/archives/xjgpak.h \
    $$PWD/archives/xpackit.h \
    $$PWD/archives/xlofi.h \
    $$PWD/archives/xsci.h \
    $$PWD/games/xagis.h \
    $$PWD/archives/xmwavez.h \
    $$PWD/compressors/xmscompresssz.h \
    $$PWD/archives/xkolibrikpack.h \
    $$PWD/documents/xmathcadpacked.h \
    $$PWD/archives/xpcommos2.h \
    $$PWD/packages/xsolarisbootarchive.h \
    $$PWD/games/xinfogramespak.h \
    $$PWD/archives/xibmzpak.h \
    $$PWD/archives/xquarterdeckqp.h \
    $$PWD/installers/xmaxisinstall.h \
    $$PWD/archives/xswagpacket.h \
    $$PWD/packages/xpalmdatabase.h \
    $$PWD/installers/xnetwareinstallfile.h \
    $$PWD/installers/xzpaksfxarchive.h \
    $$PWD/archives/xaixbff.h \
    $$PWD/archives/xaldus.h \
    $$PWD/archives/xampk.h \
    $$PWD/archives/xaodos.h \
    $$PWD/archives/xarcv2.h \
    $$PWD/archives/xarcv4.h \
    $$PWD/archives/xarpdp11.h \
    $$PWD/archives/xartipack.h \
    $$PWD/archives/xascend.h \
    $$PWD/archives/xascendbackup.h \
    $$PWD/archives/xasymetrix.h \
    $$PWD/transport/xbinaryii.h \
    $$PWD/installers/xbinshsfx.h \
    $$PWD/games/xbluebytelib.h \
    $$PWD/archives/xboo.h \
    $$PWD/archives/xborlandpack.h \
    $$PWD/games/xbsn.h \
    $$PWD/games/xbthpak.h \
    $$PWD/games/xbvrppac.h \
    $$PWD/compressors/xbzip1.h \
    $$PWD/installers/xinstallanywhere.h \
    $$PWD/installers/xpcinstall.h \
    $$PWD/installers/xpcinstallsfx.h \
    $$PWD/archives/xsqz.h \
    $$PWD/archives/xseaarc.h \
    $$PWD/core/xexternalarchive.h \
    $$PWD/archives/xfreearc.h \
    $$PWD/archives/xzpaq.h \
    $$PWD/archives/xbcm.h \
    $$PWD/archives/xlpaq8.h \
    $$PWD/archives/xpea.h \
    $$PWD/archives/xarj.h \
    $$PWD/archives/xace.h \
    $$PWD/core/xfilteredarchive.h \
    $$PWD/archives/xcab.h \
    $$PWD/archives/xcfbf.h \
    $$PWD/tar/xcpio.h \
    $$PWD/games/xpak.h \
    $$PWD/games/xhetlkb.h \
    $$PWD/games/xwad.h \
    $$PWD/games/xgrp.h \
    $$PWD/games/xgodotpck.h \
    $$PWD/games/xwbfsarchive.h \
    $$PWD/games/xrvzarchive.h \
    $$PWD/games/xhog.h \
    $$PWD/games/xwolfvswap.h \
    $$PWD/games/xwintermutedcp.h \
    $$PWD/games/xt64.h \
    $$PWD/games/xgamestorearchive_p.h \
    $$PWD/games/xckp.h \
    $$PWD/games/xedp.h \
    $$PWD/games/xmpq.h \
    $$PWD/games/xbigf.h \
    $$PWD/games/xparsecarchive.h \
    $$PWD/games/xpmm.h \
    $$PWD/archives/xwarc.h \
    $$PWD/tar/xmtree.h \
    $$PWD/transport/xshar.h \
    $$PWD/transport/xuu.h \
    $$PWD/packages/xdeb.h \
    $$PWD/filesystems/xudf.h \
    $$PWD/packages/xwim.h \
    $$PWD/packages/xrpm.h \
    $$PWD/compressors/xkwaj.h \
    $$PWD/archives/xasar.h \
    $$PWD/archives/xxar.h \
    $$PWD/archives/xzoo.h \
    $$PWD/archives/xstk.h \
    $$PWD/archives/xlha.h \
    $$PWD/archives/xsar.h \
    $$PWD/archives/xarx.h \
    $$PWD/archives/xrar.h \
    $$PWD/archives/xsevenzip.h \
    $$PWD/filesystems/xsquashfs.h \
    $$PWD/tar/xtar_bzip2.h \
    $$PWD/tar/xtar_lzip.h \
    $$PWD/tar/xtar_lzma.h \
    $$PWD/tar/xtar_lzop.h \
    $$PWD/tar/xtar_xz.h \
    $$PWD/tar/xtar_zstd.h \
    $$PWD/tar/xtar_lz4.h \
    $$PWD/compressors/xszdd.h \
    $$PWD/compressors/xbzip2.h \
    $$PWD/compressors/xbrotli.h \
    $$PWD/compressors/xlzip.h \
    $$PWD/compressors/xxz.h \
    $$PWD/compressors/xzlib.h \
    $$PWD/compressors/xzstd.h \
    $$PWD/compressors/xlz4.h \
    $$PWD/compressors/xlz5.h \
    $$PWD/compressors/xlizard.h \
    $$PWD/compressors/xlzma.h \
    $$PWD/compressors/xlzo.h \
    $$PWD/compressors/xcompressz.h \
    $$PWD/archives/xminidump.h \
    $$PWD/diskimages/xdmg.h \
    $$PWD/archives/xfpak.h \
    $$PWD/archives/xiscab.h \
    $$PWD/archives/xjugglor.h \
    $$PWD/archives/xrib.h \
    $$PWD/archives/xspis.h \
    $$PWD/core/xmaterializedunpackguard.h \
    $$PWD/diskimages/xcopyqm.h \
    $$PWD/installers/xactualinstaller.h \
    $$PWD/installers/xadvancedinstaller.h \
    $$PWD/installers/xburn.h \
    $$PWD/installers/xclickteam.h \
    $$PWD/installers/xcreateinstall.h \
    $$PWD/installers/xgentee.h \
    $$PWD/installers/xiexpress.h \
    $$PWD/installers/xinnosetup.h \
    $$PWD/installers/xinstallforge.h \
    $$PWD/installers/xinstallshield.h \
    $$PWD/installers/xmsi.h \
    $$PWD/installers/xnsis.h \
    $$PWD/installers/xpftw.h \
    $$PWD/installers/xsetupfactory.h \
    $$PWD/installers/xsmartinstall.h \
    $$PWD/installers/xtarma.h \
    $$PWD/installers/xwix.h \
    $$PWD/sfx/xarcsfx.h \
    $$PWD/sfx/xarjsfx.h \
    $$PWD/sfx/xarqsfx.h \
    $$PWD/sfx/xbsnsfx.h \
    $$PWD/sfx/xbzip2sfx.h \
    $$PWD/sfx/xcabsfx.h \
    $$PWD/sfx/xfreearcsfx.h \
    $$PWD/sfx/xgzipsfx.h \
    $$PWD/sfx/xkwajsfx.h \
    $$PWD/sfx/xlhasfx.h \
    $$PWD/sfx/xrarsfx.h \
    $$PWD/sfx/xrtpatchsfx.h \
    $$PWD/sfx/xsevenzipsfx.h \
    $$PWD/sfx/xsfx.h \
    $$PWD/sfx/xspissfx.h \
    $$PWD/sfx/xsqzsfx.h \
    $$PWD/sfx/xsydexsfxarchive.h \
    $$PWD/sfx/xszddsfx.h \
    $$PWD/sfx/xzipsfx.h \
    $$PWD/sfx/xzpaqsfx.h

SOURCES += \
    $$NSIS_BZIP2_SOURCE \
    $$PWD/tar/x_ar.cpp \
    $$PWD/archives/xsqlitearchive.cpp \
    $$PWD/archives/xcpmcompressedarchive.cpp \
    $$PWD/Algos/xcpmcrunchdecoder.cpp \
    $$PWD/archives/xgitobjectarchive.cpp \
    $$PWD/archives/xalzarchive.cpp \
    $$PWD/archives/xfreearcnative.cpp \
    $$PWD/Algos/xfreearcdecoder.cpp \
    $$PWD/archives/xrziparchive.cpp \
    $$PWD/documents/xchmarchive.cpp \
    $$PWD/filesystems/xntfsarchive.cpp \
    $$PWD/games/xhog2.cpp \
    $$PWD/games/xpboarchive.cpp \
    $$PWD/Algos/xrzipdecoder.cpp \
    $$PWD/diskimages/xvirtualdiskarchive.cpp \
    $$PWD/archives/xancient.cpp \
    $$PWD/transport/xlegacyencoded.cpp \
    $$PWD/archives/xdearkarchive.cpp \
    $$PWD/diskimages/xdskexp.cpp \
    $$PWD/diskimages/xlibdskarchive.cpp \
    $$PWD/diskimages/xadfarchive.cpp \
    $$PWD/archives/xcompactproarchive.cpp \
    $$PWD/archives/xdiskdoublerarchive.cpp \
    $$PWD/archives/xfls.cpp \
    $$PWD/archives/xpyinstallercarchive.cpp \
    $$PWD/installers/xwisesfxarchive.cpp \
    $$PWD/installers/xis3sfxarchive.cpp \
    $$PWD/installers/xis14sfxarchive.cpp \
    $$PWD/core/xlegacystorearchive.cpp \
    $$PWD/archives/xconcatziparchive.cpp \
    $$PWD/archives/xwinimageziparchive.cpp \
    $$PWD/diskimages/xdiskjugglerarchive.cpp \
    $$PWD/transport/xapplesingle.cpp \
    $$PWD/diskimages/x2img.cpp \
    $$PWD/archives/xpyz.cpp \
    $$PWD/archives/xlzxarchive.cpp \
    $$PWD/archives/xmi10archive.cpp \
    $$PWD/transport/xmacbinary.cpp \
    $$PWD/transport/xresourcefork.cpp \
    $$PWD/archives/xlbr.cpp \
    $$PWD/archives/xrtpatch.cpp \
    $$PWD/compressors/xrncarchive.cpp \
    $$PWD/archives/xlarcpfx.cpp \
    $$PWD/archives/xarq.cpp \
    $$PWD/archives/xnetwarepackedfile.cpp \
    $$PWD/archives/xpovlablzh.cpp \
    $$PWD/archives/xearefpack.cpp \
    $$PWD/documents/xprintshopdeluxe.cpp \
    $$PWD/archives/xfrontpagetheme.cpp \
    $$PWD/archives/xsecondnature.cpp \
    $$PWD/compressors/xlzpis2.cpp \
    $$PWD/documents/xfinereaderpack.cpp \
    $$PWD/archives/xecmpacked.cpp \
    $$PWD/games/xgstpack.cpp \
    $$PWD/archives/xnpack.cpp \
    $$PWD/archives/xcorelltec.cpp \
    $$PWD/archives/xirwinpac.cpp \
    $$PWD/archives/xdtpacked.cpp \
    $$PWD/compressors/xgashuff.cpp \
    $$PWD/archives/xpowerboardbbs.cpp \
    $$PWD/archives/xclayarchive.cpp \
    $$PWD/archives/xsclarchive.cpp \
    $$PWD/diskimages/xfdiimage.cpp \
    $$PWD/diskimages/xpcmimage.cpp \
    $$PWD/archives/xpowerarc.cpp \
    $$PWD/diskimages/xapricotimage.cpp \
    $$PWD/diskimages/xcisoimage.cpp \
    $$PWD/diskimages/xcloopimage.cpp \
    $$PWD/archives/xbigafarchive.cpp \
    $$PWD/filesystems/xromfsarchive.cpp \
    $$PWD/archives/xchieflzarchive.cpp \
    $$PWD/archives/xhaarchive.cpp \
    $$PWD/archives/xclparchive.cpp \
    $$PWD/archives/xlimarchive.cpp \
    $$PWD/archives/xainarchive.cpp \
    $$PWD/archives/xobfuscatedarchive.cpp \
    $$PWD/archives/xuleadarchive.cpp \
    $$PWD/archives/xtopspeedarchive.cpp \
    $$PWD/archives/xtwsarchive.cpp \
    $$PWD/archives/xzzarchive.cpp \
    $$PWD/archives/xcruarchive.cpp \
    $$PWD/installers/xsfxgziparchive.cpp \
    $$PWD/tar/xtarx2archive.cpp \
    $$PWD/archives/xsqxarchive.cpp \
    $$PWD/archives/xpakleoarchive.cpp \
    $$PWD/archives/xtpsarchive.cpp \
    $$PWD/archives/xtgcfarchive.cpp \
    $$PWD/archives/xzxziparchive.cpp \
    $$PWD/archives/ximparchive.cpp \
    $$PWD/archives/xsfpackarchive.cpp \
    $$PWD/archives/xvmarcarchive.cpp \
    $$PWD/archives/xtersearchive.cpp \
    $$PWD/diskimages/xvmdkarchive.cpp \
    $$PWD/filesystems/xsquashfsarchive.cpp \
    $$PWD/archives/xpanoramaarchive.cpp \
    $$PWD/packages/xvmssavesetarchive.cpp \
    $$PWD/archives/xziearchive.cpp \
    $$PWD/diskimages/xteledeskarchive.cpp \
    $$PWD/games/xteacyarchive.cpp \
    $$PWD/diskimages/xx64archive.cpp \
    $$PWD/archives/xchieflzmultiarchive.cpp \
    $$PWD/archives/xcflarchive.cpp \
    $$PWD/transport/xtnefarchive.cpp \
    $$PWD/archives/xqdaarchive.cpp \
    $$PWD/archives/xdpkarchive.cpp \
    $$PWD/archives/xdsl2archive.cpp \
    $$PWD/archives/xzlwbarchive.cpp \
    $$PWD/archives/xc64wraptorarchive.cpp \
    $$PWD/packages/xvmsdatabasearchive.cpp \
    $$PWD/tar/xtarx1archive.cpp \
    $$PWD/packages/xvmspcsiarchive.cpp \
    $$PWD/archives/xzaparchive.cpp \
    $$PWD/archives/xtrcpakarchive.cpp \
    $$PWD/archives/xzzzarchive.cpp \
    $$PWD/archives/xzfsfarchive.cpp \
    $$PWD/archives/xti99arcarchive.cpp \
    $$PWD/tar/xtarnextsteparchive.cpp \
    $$PWD/diskimages/xtrdosarchive.cpp \
    $$PWD/archives/xxeditpackarchive.cpp \
    $$PWD/archives/xzoomarchive.cpp \
    $$PWD/archives/xzcmparchive.cpp \
    $$PWD/archives/xwintersoftarchive.cpp \
    $$PWD/archives/xzpakarchive.cpp \
    $$PWD/archives/xztcarchive.cpp \
    $$PWD/archives/xtivoliarchive.cpp \
    $$PWD/archives/xwpkarchive.cpp \
    $$PWD/archives/xtrcarchive.cpp \
    $$PWD/diskimages/xcopyqmarchive.cpp \
    $$PWD/archives/xkboomarchive.cpp \
    $$PWD/archives/xbigfarchive.cpp \
    $$PWD/archives/xarcfs.cpp \
    $$PWD/archives/xcmparchive.cpp \
    $$PWD/packages/xbeospackage.cpp \
    $$PWD/games/xsilmarils.cpp \
    $$PWD/installers/xis7inx.cpp \
    $$PWD/archives/xrawlzw15v.cpp \
    $$PWD/archives/xlbrcobol.cpp \
    $$PWD/archives/xlsz.cpp \
    $$PWD/games/xgob.cpp \
    $$PWD/archives/xgtu.cpp \
    $$PWD/documents/xnotetab.cpp \
    $$PWD/installers/xizpack.cpp \
    $$PWD/packages/xsolarispackage.cpp \
    $$PWD/archives/xhlb.cpp \
    $$PWD/archives/xrid.cpp \
    $$PWD/archives/xrompaq.cpp \
    $$PWD/archives/xfiz.cpp \
    $$PWD/archives/xmiz.cpp \
    $$PWD/archives/xibmspack.cpp \
    $$PWD/archives/xea.cpp \
    $$PWD/archives/xsls.cpp \
    $$PWD/archives/xpcsecure.cpp \
    $$PWD/diskimages/xpmdiskcopy.cpp \
    $$PWD/games/xmegatechvol.cpp \
    $$PWD/archives/xigf1.cpp \
    $$PWD/archives/xjetbbs.cpp \
    $$PWD/installers/xmakeself.cpp \
    $$PWD/archives/xfld.cpp \
    $$PWD/archives/xglu.cpp \
    $$PWD/archives/xjam.cpp \
    $$PWD/archives/xfmc1.cpp \
    $$PWD/archives/xsoftpaq2.cpp \
    $$PWD/archives/xmarc.cpp \
    $$PWD/archives/xstork.cpp \
    $$PWD/archives/xseadata.cpp \
    $$PWD/archives/xqnxbase.cpp \
    $$PWD/archives/xgamos.cpp \
    $$PWD/archives/xsos.cpp \
    $$PWD/documents/xexesbookbuilder.cpp \
    $$PWD/compressors/xhuff.cpp \
    $$PWD/archives/xlzhcxp.cpp \
    $$PWD/archives/xkrml.cpp \
    $$PWD/archives/xqip1.cpp \
    $$PWD/archives/xquantum.cpp \
    $$PWD/archives/xirixsa.cpp \
    $$PWD/archives/xjm93.cpp \
    $$PWD/diskimages/xnextstepdiskimage.cpp \
    $$PWD/archives/xmva.cpp \
    $$PWD/archives/xpkt.cpp \
    $$PWD/diskimages/xhdcopy.cpp \
    $$PWD/archives/xivt.cpp \
    $$PWD/archives/xswag.cpp \
    $$PWD/archives/xstylus.cpp \
    $$PWD/games/xsettlersft.cpp \
    $$PWD/archives/xriversoft.cpp \
    $$PWD/installers/xgksetup.cpp \
    $$PWD/packages/xopc.cpp \
    $$PWD/games/xgob2.cpp \
    $$PWD/compressors/xsq.cpp \
    $$PWD/compressors/xoraclesqueeze.cpp \
    $$PWD/installers/xis11.cpp \
    $$PWD/documents/xrecognita.cpp \
    $$PWD/archives/xinteduft.cpp \
    $$PWD/documents/xpaperport.cpp \
    $$PWD/archives/xealib.cpp \
    $$PWD/archives/xnid.cpp \
    $$PWD/archives/xhap.cpp \
    $$PWD/documents/xexeebookcreator.cpp \
    $$PWD/compressors/xlzdiet.cpp \
    $$PWD/archives/xqualitas.cpp \
    $$PWD/compressors/xlzv1.cpp \
    $$PWD/compressors/xxpakarchive.cpp \
    $$PWD/archives/xsw.cpp \
    $$PWD/archives/xsaf.cpp \
    $$PWD/archives/xigf2.cpp \
    $$PWD/archives/xrcf.cpp \
    $$PWD/diskimages/xhfe.cpp \
    $$PWD/archives/xrsvk.cpp \
    $$PWD/archives/xhzl.cpp \
    $$PWD/archives/xjbf.cpp \
    $$PWD/archives/xjgpak.cpp \
    $$PWD/archives/xpackit.cpp \
    $$PWD/archives/xlofi.cpp \
    $$PWD/archives/xsci.cpp \
    $$PWD/games/xagis.cpp \
    $$PWD/archives/xmwavez.cpp \
    $$PWD/compressors/xmscompresssz.cpp \
    $$PWD/archives/xkolibrikpack.cpp \
    $$PWD/documents/xmathcadpacked.cpp \
    $$PWD/archives/xpcommos2.cpp \
    $$PWD/packages/xsolarisbootarchive.cpp \
    $$PWD/games/xinfogramespak.cpp \
    $$PWD/archives/xibmzpak.cpp \
    $$PWD/archives/xquarterdeckqp.cpp \
    $$PWD/installers/xmaxisinstall.cpp \
    $$PWD/archives/xswagpacket.cpp \
    $$PWD/packages/xpalmdatabase.cpp \
    $$PWD/installers/xnetwareinstallfile.cpp \
    $$PWD/installers/xzpaksfxarchive.cpp \
    $$PWD/archives/xaixbff.cpp \
    $$PWD/archives/xaldus.cpp \
    $$PWD/archives/xampk.cpp \
    $$PWD/archives/xaodos.cpp \
    $$PWD/archives/xarcv2.cpp \
    $$PWD/archives/xarcv4.cpp \
    $$PWD/archives/xarpdp11.cpp \
    $$PWD/archives/xartipack.cpp \
    $$PWD/archives/xascend.cpp \
    $$PWD/archives/xascendbackup.cpp \
    $$PWD/archives/xasymetrix.cpp \
    $$PWD/transport/xbinaryii.cpp \
    $$PWD/installers/xbinshsfx.cpp \
    $$PWD/games/xbluebytelib.cpp \
    $$PWD/archives/xboo.cpp \
    $$PWD/archives/xborlandpack.cpp \
    $$PWD/games/xbsn.cpp \
    $$PWD/games/xbthpak.cpp \
    $$PWD/games/xbvrppac.cpp \
    $$PWD/compressors/xbzip1.cpp \
    $$PWD/installers/xinstallanywhere.cpp \
    $$PWD/installers/xpcinstall.cpp \
    $$PWD/installers/xpcinstallsfx.cpp \
    $$PWD/archives/xsqz.cpp \
    $$PWD/archives/xseaarc.cpp \
    $$PWD/core/xexternalarchive.cpp \
    $$PWD/archives/xfreearc.cpp \
    $$PWD/archives/xzpaq.cpp \
    $$PWD/archives/xbcm.cpp \
    $$PWD/archives/xlpaq8.cpp \
    $$PWD/archives/xpea.cpp \
    $$PWD/archives/xarj.cpp \
    $$PWD/archives/xace.cpp \
    $$PWD/core/xfilteredarchive.cpp \
    $$PWD/archives/xcab.cpp \
    $$PWD/archives/xcfbf.cpp \
    $$PWD/tar/xcpio.cpp \
    $$PWD/games/xpak.cpp \
    $$PWD/games/xhetlkb.cpp \
    $$PWD/games/xwad.cpp \
    $$PWD/games/xgrp.cpp \
    $$PWD/games/xgodotpck.cpp \
    $$PWD/games/xwbfsarchive.cpp \
    $$PWD/games/xrvzarchive.cpp \
    $$PWD/games/xhog.cpp \
    $$PWD/games/xwolfvswap.cpp \
    $$PWD/games/xwintermutedcp.cpp \
    $$PWD/games/xt64.cpp \
    $$PWD/games/xgamestorearchive_p.cpp \
    $$PWD/games/xckp.cpp \
    $$PWD/games/xedp.cpp \
    $$PWD/games/xmpq.cpp \
    $$PWD/games/xbigf.cpp \
    $$PWD/games/xparsecarchive.cpp \
    $$PWD/games/xpmm.cpp \
    $$PWD/archives/xwarc.cpp \
    $$PWD/tar/xmtree.cpp \
    $$PWD/transport/xshar.cpp \
    $$PWD/transport/xuu.cpp \
    $$PWD/packages/xdeb.cpp \
    $$PWD/filesystems/xudf.cpp \
    $$PWD/packages/xwim.cpp \
    $$PWD/packages/xrpm.cpp \
    $$PWD/compressors/xkwaj.cpp \
    $$PWD/archives/xasar.cpp \
    $$PWD/archives/xxar.cpp \
    $$PWD/archives/xzoo.cpp \
    $$PWD/archives/xstk.cpp \
    $$PWD/archives/xlha.cpp \
    $$PWD/archives/xsar.cpp \
    $$PWD/archives/xarx.cpp \
    $$PWD/archives/xrar.cpp \
    $$PWD/archives/xsevenzip.cpp \
    $$PWD/filesystems/xsquashfs.cpp \
    $$PWD/tar/xtar_bzip2.cpp \
    $$PWD/tar/xtar_lzip.cpp \
    $$PWD/tar/xtar_lzma.cpp \
    $$PWD/tar/xtar_lzop.cpp \
    $$PWD/tar/xtar_xz.cpp \
    $$PWD/tar/xtar_zstd.cpp \
    $$PWD/tar/xtar_lz4.cpp \
    $$PWD/compressors/xszdd.cpp \
    $$PWD/compressors/xbzip2.cpp \
    $$PWD/compressors/xbrotli.cpp \
    $$PWD/compressors/xlzip.cpp \
    $$PWD/compressors/xxz.cpp \
    $$PWD/compressors/xzlib.cpp \
    $$PWD/compressors/xzstd.cpp \
    $$PWD/compressors/xlz4.cpp \
    $$PWD/compressors/xlz5.cpp \
    $$PWD/compressors/xlizard.cpp \
    $$PWD/compressors/xlzma.cpp \
    $$PWD/compressors/xlzo.cpp \
    $$PWD/compressors/xcompressz.cpp \
    $$PWD/archives/xminidump.cpp \
    $$PWD/diskimages/xdmg.cpp \
    $$PWD/archives/xfpak.cpp \
    $$PWD/archives/xiscab.cpp \
    $$PWD/archives/xjugglor.cpp \
    $$PWD/archives/xrib.cpp \
    $$PWD/archives/xspis.cpp \
    $$PWD/diskimages/xcopyqm.cpp \
    $$PWD/installers/xactualinstaller.cpp \
    $$PWD/installers/xadvancedinstaller.cpp \
    $$PWD/installers/xburn.cpp \
    $$PWD/installers/xclickteam.cpp \
    $$PWD/installers/xcreateinstall.cpp \
    $$PWD/installers/xgentee.cpp \
    $$PWD/installers/xiexpress.cpp \
    $$PWD/installers/xinnosetup.cpp \
    $$PWD/installers/xinstallforge.cpp \
    $$PWD/installers/xinstallshield.cpp \
    $$PWD/installers/xmsi.cpp \
    $$PWD/installers/xnsis.cpp \
    $$PWD/installers/xpftw.cpp \
    $$PWD/installers/xsetupfactory.cpp \
    $$PWD/installers/xsmartinstall.cpp \
    $$PWD/installers/xtarma.cpp \
    $$PWD/installers/xwix.cpp \
    $$PWD/sfx/xarcsfx.cpp \
    $$PWD/sfx/xarjsfx.cpp \
    $$PWD/sfx/xarqsfx.cpp \
    $$PWD/sfx/xbsnsfx.cpp \
    $$PWD/sfx/xbzip2sfx.cpp \
    $$PWD/sfx/xcabsfx.cpp \
    $$PWD/sfx/xfreearcsfx.cpp \
    $$PWD/sfx/xgzipsfx.cpp \
    $$PWD/sfx/xkwajsfx.cpp \
    $$PWD/sfx/xlhasfx.cpp \
    $$PWD/sfx/xrarsfx.cpp \
    $$PWD/sfx/xrtpatchsfx.cpp \
    $$PWD/sfx/xsevenzipsfx.cpp \
    $$PWD/sfx/xsfx.cpp \
    $$PWD/sfx/xspissfx.cpp \
    $$PWD/sfx/xsqzsfx.cpp \
    $$PWD/sfx/xsydexsfxarchive.cpp \
    $$PWD/sfx/xszddsfx.cpp \
    $$PWD/sfx/xzipsfx.cpp \
    $$PWD/sfx/xzpaqsfx.cpp

DISTFILES += \
    $$PWD/LICENSE \
    $$PWD/README.md \
    $$PWD/xarchive.cmake
