include_directories(${CMAKE_CURRENT_LIST_DIR})
include_directories(${CMAKE_CURRENT_LIST_DIR}/Algos/)
# The 7-Zip C public headers (LzmaDec.h, Ppmd7.h, 7zTypes.h, ...) live in
# Algos/include, kept apart from the first-party and generated sources.
# Consumers outside XArchive -- XStaticUnpacker's xnsis.cpp and xmew.cpp
# include LzmaDec.h -- resolve them from here without the vendored tree.
include_directories(${CMAKE_CURRENT_LIST_DIR}/Algos/include/)
# bzip2 headers (bzlib.h) moved to Algos/include with its sources; that path
# is already on the include list above.
# zlib headers moved to Algos/include with its sources; that path is already
# on the include list above.

if (NOT DEFINED XBINARY_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../Formats/xbinary.cmake)
    set(XARCHIVE_SOURCES ${XARCHIVE_SOURCES} ${XBINARY_SOURCES})
endif()

if (NOT DEFINED XOPTIONS_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/../XOptions/xoptions.cmake)
    set(XARCHIVE_SOURCES ${XARCHIVE_SOURCES} ${XOPTIONS_SOURCES})
endif()

#include(${CMAKE_CURRENT_LIST_DIR}/../Formats/exec/xmach.cmake)

set(XARCHIVE_SOURCES
    ${XARCHIVE_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/x_ar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/x_ar.h
    ${CMAKE_CURRENT_LIST_DIR}/xapk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xapk.h
    ${CMAKE_CURRENT_LIST_DIR}/xapks.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xapks.h
    ${CMAKE_CURRENT_LIST_DIR}/xseaarc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xseaarc.h
    ${CMAKE_CURRENT_LIST_DIR}/xfreearc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfreearc.h
    ${CMAKE_CURRENT_LIST_DIR}/xarj.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarj.h
    ${CMAKE_CURRENT_LIST_DIR}/xace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xace.h
    ${CMAKE_CURRENT_LIST_DIR}/xarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xfilteredarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfilteredarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xcab.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcab.h
    ${CMAKE_CURRENT_LIST_DIR}/xcfbf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcfbf.h
    ${CMAKE_CURRENT_LIST_DIR}/xcpio.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcpio.h
    ${CMAKE_CURRENT_LIST_DIR}/xgamearchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgamearchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xwarc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xwarc.h
    ${CMAKE_CURRENT_LIST_DIR}/xmtree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmtree.h
    ${CMAKE_CURRENT_LIST_DIR}/xuu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xuu.h
    ${CMAKE_CURRENT_LIST_DIR}/xcompress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcompress.h
    ${CMAKE_CURRENT_LIST_DIR}/xdecompress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdecompress.h
    ${CMAKE_CURRENT_LIST_DIR}/xcompresseddevice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcompresseddevice.h
    ${CMAKE_CURRENT_LIST_DIR}/xdeb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdeb.h
    ${CMAKE_CURRENT_LIST_DIR}/xgzip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgzip.h
    ${CMAKE_CURRENT_LIST_DIR}/xipa.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xipa.h
    ${CMAKE_CURRENT_LIST_DIR}/xiso9660.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xiso9660.h
    ${CMAKE_CURRENT_LIST_DIR}/xudf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xudf.h
    ${CMAKE_CURRENT_LIST_DIR}/xwim.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xwim.h
    ${CMAKE_CURRENT_LIST_DIR}/xrpm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrpm.h
    ${CMAKE_CURRENT_LIST_DIR}/xkwaj.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xkwaj.h
    ${CMAKE_CURRENT_LIST_DIR}/xasar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xasar.h
    ${CMAKE_CURRENT_LIST_DIR}/xxar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xxar.h
    ${CMAKE_CURRENT_LIST_DIR}/xzoo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xzoo.h
    ${CMAKE_CURRENT_LIST_DIR}/xjar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xjar.h
    ${CMAKE_CURRENT_LIST_DIR}/xlha.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsar.h
    ${CMAKE_CURRENT_LIST_DIR}/xarx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarx.h
    ${CMAKE_CURRENT_LIST_DIR}/xlha.h
    ${CMAKE_CURRENT_LIST_DIR}/xmachofat.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmachofat.h
    ${CMAKE_CURRENT_LIST_DIR}/xrar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrar.h
    ${CMAKE_CURRENT_LIST_DIR}/xsevenzip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsevenzip.h
    ${CMAKE_CURRENT_LIST_DIR}/xarchives_ip7z.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsquashfs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsquashfs.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_bzip2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_bzip2.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_compress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_compress.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_gz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_gz.h
    ${CMAKE_CURRENT_LIST_DIR}/xtarcompressed.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtarcompressed.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzip.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzma.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzma.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzop.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_xz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_xz.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_zstd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_zstd.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lz4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lz4.h
    ${CMAKE_CURRENT_LIST_DIR}/xzstd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xzstd.h
    ${CMAKE_CURRENT_LIST_DIR}/xlz4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlz4.h
    ${CMAKE_CURRENT_LIST_DIR}/xlz5.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlz5.h
    ${CMAKE_CURRENT_LIST_DIR}/xlizard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlizard.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzma.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzma.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzo.h
    ${CMAKE_CURRENT_LIST_DIR}/xcompressz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcompressz.h
    ${CMAKE_CURRENT_LIST_DIR}/xzip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xzip.h
    ${CMAKE_CURRENT_LIST_DIR}/xzlib.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xzlib.h
    ${CMAKE_CURRENT_LIST_DIR}/xnpm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xnpm.h
    ${CMAKE_CURRENT_LIST_DIR}/xdos16.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdos16.h
    ${CMAKE_CURRENT_LIST_DIR}/xszdd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xszdd.h
    ${CMAKE_CURRENT_LIST_DIR}/xbzip2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbzip2.h
    ${CMAKE_CURRENT_LIST_DIR}/xbrotli.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbrotli.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzip.h
    ${CMAKE_CURRENT_LIST_DIR}/xxz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xxz.h
    ${CMAKE_CURRENT_LIST_DIR}/xminidump.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xminidump.h
    ${CMAKE_CURRENT_LIST_DIR}/xdmg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdmg.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/algo_utils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/algo_utils.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xalgo_local.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xarcdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xarcdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xarjdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xarjdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xacedecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xacedecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xucldecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xucldecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xucldecoder_acc.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzhdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzhdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xkwajlzssdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xkwajlzssdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xkwajlzhdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xkwajlzhdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xrardecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xrardecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xit214decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xit214decoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xdeflatedecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xdeflatedecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/ximplodedecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/ximplodedecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzmadecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzmadecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzwdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzwdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xascii85decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xascii85decoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xasciihexdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xasciihexdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xrunlengthdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xrunlengthdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xstoredecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xstoredecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xbzip2decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xbzip2decoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xbrotlidecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xbrotlidecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzssdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzssdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xshrinkdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xshrinkdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xreducedecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xreducedecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xzipcryptodecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xzipcryptodecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xppmddecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xppmddecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xppmdrangedecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xppmdrangedecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xppmdmodel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xppmdmodel.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xppmd7model.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xppmd7model.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xaesdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xaesdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xbcj2decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xbcj2decoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xbranchdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xbranchdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzxdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzxdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xxpressdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xxpressdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xsha256decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xsha256decoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xblake2sp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xblake2sp.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xzstddecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xzstddecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlz4decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlz4decoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlz5decoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlz5decoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlizarddecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlizarddecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/lz5lizarddeclib.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/lz4declib.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/zstdlegacydeclib.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/zstddeclib.cpp
    # The five entries below were converted from C to C++ on 2026-08-17 and must
    # stay C++: they define ZSTDv05/06/07_* and ZBUFFv07_* symbols that no header
    # declares, so a C build of one and a C++ build of its caller fail at link,
    # not at compile. Each file carries an #ifndef __cplusplus / #error guard.
    ${CMAKE_CURRENT_LIST_DIR}/Algos/zstd_xxhash.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/zstdlegacy_v04.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/zstdlegacy_v05.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/zstdlegacy_v06.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/zstdlegacy_v07.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzodecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xlzodecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xcompressdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xcompressdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/lz4declib.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/lz5lizarddeclib.cpp
)
