INCLUDEPATH += $$PWD
DEPENDPATH += $$PWD
INCLUDEPATH += $$PWD/Algos
DEPENDPATH += $$PWD/Algos
INCLUDEPATH += $$PWD/Algos/include
DEPENDPATH += $$PWD/Algos/include

# The shared core (all classes relocated to Formats, XCompress/XDecompress,
# ALL Algos decoders, and xbinary/xoptions/xpng/xjavaclass/xandroidbinary)
# lives in xzip.pri so it can be used WITHOUT the USE_ARCHIVE define; this file
# adds only the formats that remain in XArchive.
!contains(XCONFIG, xzip) {
    XCONFIG += xzip
    include($$PWD/xzip.pri)
}

include($$PWD/deark.pri)
include($$PWD/legacydisk.pri)

HEADERS += \
    $$PWD/x_ar.h \
    $$PWD/xsqlitearchive.h \
    $$PWD/xcpmcompressedarchive.h \
    $$PWD/Algos/xu3cpmdecoder.h \
    $$PWD/xgitobjectarchive.h \
    $$PWD/xalzarchive.h \
    $$PWD/xfreearcnative.h \
    $$PWD/Algos/xfreearcdecoder.h \
    $$PWD/xrziparchive.h \
    $$PWD/xchmarchive.h \
    $$PWD/xntfsarchive.h \
    $$PWD/games/xhog2.h \
    $$PWD/games/xpboarchive.h \
    $$PWD/Algos/xu3rzipdecoder.h \
    $$PWD/xvirtualdiskarchive.h \
    $$PWD/xancient.h \
    $$PWD/xlegacyencoded.h \
    $$PWD/xdearkarchive.h \
    $$PWD/xdskexp.h \
    $$PWD/xlibdskarchive.h \
    $$PWD/xadfarchive.h \
    $$PWD/xcompactproarchive.h \
    $$PWD/xdiskdoublerarchive.h \
    $$PWD/xfls.h \
    $$PWD/xpyinstallercarchive.h \
    $$PWD/xwisesfxarchive.h \
    $$PWD/xis3sfxarchive.h \
    $$PWD/xis14sfxarchive.h \
    $$PWD/xlegacystorearchive.h \
    $$PWD/xconcatziparchive.h \
    $$PWD/xdiskjugglerarchive.h \
    $$PWD/xapplesingle.h \
    $$PWD/x2img.h \
    $$PWD/xpyz.h \
    $$PWD/xlzxarchive.h \
    $$PWD/xmi10archive.h \
    $$PWD/xmacbinary.h \
    $$PWD/xresourcefork.h \
    $$PWD/xlbr.h \
    $$PWD/xrtpatch.h \
    $$PWD/xrncarchive.h \
    $$PWD/xarq.h \
    $$PWD/xnetwarepackedfile.h \
    $$PWD/xpovlablzh.h \
    $$PWD/xearefpack.h \
    $$PWD/xprintshopdeluxe.h \
    $$PWD/xfrontpagetheme.h \
    $$PWD/xsecondnature.h \
    $$PWD/xlzpis2.h \
    $$PWD/xfinereaderpack.h \
    $$PWD/xecmpacked.h \
    $$PWD/xgstpack.h \
    $$PWD/xnpack.h \
    $$PWD/xcorelltec.h \
    $$PWD/xirwinpac.h \
    $$PWD/xdtpacked.h \
    $$PWD/xgashuff.h \
    $$PWD/xpowerboardbbs.h \
    $$PWD/xsilmarils.h \
    $$PWD/xis7inx.h \
    $$PWD/xrawlzw15v.h \
    $$PWD/xlbrcobol.h \
    $$PWD/xlsz.h \
    $$PWD/xgob.h \
    $$PWD/xgtu.h \
    $$PWD/xnotetab.h \
    $$PWD/xizpack.h \
    $$PWD/xsolarispackage.h \
    $$PWD/xhlb.h \
    $$PWD/xrid.h \
    $$PWD/xrompaq.h \
    $$PWD/xfiz.h \
    $$PWD/xmiz.h \
    $$PWD/xibmspack.h \
    $$PWD/xea.h \
    $$PWD/xsls.h \
    $$PWD/xpcsecure.h \
    $$PWD/xpmdiskcopy.h \
    $$PWD/xmegatechvol.h \
    $$PWD/xigf1.h \
    $$PWD/xjetbbs.h \
    $$PWD/xmakeself.h \
    $$PWD/xfld.h \
    $$PWD/xglu.h \
    $$PWD/xjam.h \
    $$PWD/xfmc1.h \
    $$PWD/xsoftpaq2.h \
    $$PWD/xmarc.h \
    $$PWD/xstork.h \
    $$PWD/xseadata.h \
    $$PWD/xqnxbase.h \
    $$PWD/xgamos.h \
    $$PWD/xsos.h \
    $$PWD/xexesbookbuilder.h \
    $$PWD/xhuff.h \
    $$PWD/xlzhcxp.h \
    $$PWD/xkrml.h \
    $$PWD/xqip1.h \
    $$PWD/xquantum.h \
    $$PWD/xirixsa.h \
    $$PWD/xjm93.h \
    $$PWD/xnextstepdiskimage.h \
    $$PWD/xmva.h \
    $$PWD/xpkt.h \
    $$PWD/xhdcopy.h \
    $$PWD/xivt.h \
    $$PWD/xswag.h \
    $$PWD/xstylus.h \
    $$PWD/xsettlersft.h \
    $$PWD/xriversoft.h \
    $$PWD/xgksetup.h \
    $$PWD/xopc.h \
    $$PWD/xgob2.h \
    $$PWD/xsq.h \
    $$PWD/xis11.h \
    $$PWD/xrecognita.h \
    $$PWD/xinteduft.h \
    $$PWD/xpaperport.h \
    $$PWD/xealib.h \
    $$PWD/xnid.h \
    $$PWD/xhap.h \
    $$PWD/xexeebookcreator.h \
    $$PWD/xlzdiet.h \
    $$PWD/xqualitas.h \
    $$PWD/xlzv1.h \
    $$PWD/xsw.h \
    $$PWD/xsaf.h \
    $$PWD/xigf2.h \
    $$PWD/xrcf.h \
    $$PWD/xhfe.h \
    $$PWD/xrsvk.h \
    $$PWD/xhzl.h \
    $$PWD/xjbf.h \
    $$PWD/xjgpak.h \
    $$PWD/xpackit.h \
    $$PWD/xlofi.h \
    $$PWD/xsci.h \
    $$PWD/xagis.h \
    $$PWD/xmwavez.h \
    $$PWD/xmscompresssz.h \
    $$PWD/xkolibrikpack.h \
    $$PWD/xmathcadpacked.h \
    $$PWD/xpcommos2.h \
    $$PWD/xsolarisbootarchive.h \
    $$PWD/xinfogramespak.h \
    $$PWD/xibmzpak.h \
    $$PWD/xquarterdeckqp.h \
    $$PWD/xmaxisinstall.h \
    $$PWD/xswagpacket.h \
    $$PWD/xpalmdatabase.h \
    $$PWD/xnetwareinstallfile.h \
    $$PWD/xaixbff.h \
    $$PWD/xaldus.h \
    $$PWD/xampk.h \
    $$PWD/xaodos.h \
    $$PWD/xarcv2.h \
    $$PWD/xarcv4.h \
    $$PWD/xarpdp11.h \
    $$PWD/xartipack.h \
    $$PWD/xascend.h \
    $$PWD/xascendbackup.h \
    $$PWD/xasymetrix.h \
    $$PWD/xbinaryii.h \
    $$PWD/xbinshsfx.h \
    $$PWD/xbluebytelib.h \
    $$PWD/xboo.h \
    $$PWD/xborlandpack.h \
    $$PWD/xbsn.h \
    $$PWD/xbthpak.h \
    $$PWD/xbvrppac.h \
    $$PWD/xbzip1.h \
    $$PWD/xinstallanywhere.h \
    $$PWD/xpcinstall.h \
    $$PWD/xsqz.h \
    $$PWD/xseaarc.h \
    $$PWD/xexternalarchive.h \
    $$PWD/xfreearc.h \
    $$PWD/xzpaq.h \
    $$PWD/xbcm.h \
    $$PWD/xlpaq8.h \
    $$PWD/xpea.h \
    $$PWD/xarj.h \
    $$PWD/xace.h \
    $$PWD/xfilteredarchive.h \
    $$PWD/xcab.h \
    $$PWD/xcfbf.h \
    $$PWD/xcpio.h \
    $$PWD/games/xpak.h \
    $$PWD/games/xwad.h \
    $$PWD/games/xgrp.h \
    $$PWD/games/xgodotpck.h \
    $$PWD/games/xwbfsarchive.h \
    $$PWD/games/xrvzarchive.h \
    $$PWD/games/xhog.h \
    $$PWD/games/xwolfvswap.h \
    $$PWD/games/xwintermutedcp.h \
    $$PWD/games/xt64.h \
    $$PWD/games/xgamestorearchive_p.h \
    $$PWD/games/xckp.h \
    $$PWD/games/xedp.h \
    $$PWD/games/xmpq.h \
    $$PWD/games/xbigf.h \
    $$PWD/games/xparsecarchive.h \
    $$PWD/games/xpmm.h \
    $$PWD/xwarc.h \
    $$PWD/xmtree.h \
    $$PWD/xshar.h \
    $$PWD/xuu.h \
    $$PWD/xdeb.h \
    $$PWD/xudf.h \
    $$PWD/xwim.h \
    $$PWD/xrpm.h \
    $$PWD/xkwaj.h \
    $$PWD/xasar.h \
    $$PWD/xxar.h \
    $$PWD/xzoo.h \
    $$PWD/xstk.h \
    $$PWD/xlha.h \
    $$PWD/xsar.h \
    $$PWD/xarx.h \
    $$PWD/xrar.h \
    $$PWD/xsevenzip.h \
    $$PWD/xsquashfs.h \
    $$PWD/xtar_bzip2.h \
    $$PWD/xtar_lzip.h \
    $$PWD/xtar_lzma.h \
    $$PWD/xtar_lzop.h \
    $$PWD/xtar_xz.h \
    $$PWD/xtar_zstd.h \
    $$PWD/xtar_lz4.h \
    $$PWD/xszdd.h \
    $$PWD/xbzip2.h \
    $$PWD/xbrotli.h \
    $$PWD/xlzip.h \
    $$PWD/xxz.h \
    $$PWD/xzlib.h \
    $$PWD/xzstd.h \
    $$PWD/xlz4.h \
    $$PWD/xlz5.h \
    $$PWD/xlizard.h \
    $$PWD/xlzma.h \
    $$PWD/xlzo.h \
    $$PWD/xcompressz.h \
    $$PWD/xminidump.h \
    $$PWD/xdmg.h

SOURCES += \
    $$PWD/x_ar.cpp \
    $$PWD/xsqlitearchive.cpp \
    $$PWD/xcpmcompressedarchive.cpp \
    $$PWD/Algos/xu3cpmdecoder.cpp \
    $$PWD/xgitobjectarchive.cpp \
    $$PWD/xalzarchive.cpp \
    $$PWD/xfreearcnative.cpp \
    $$PWD/Algos/xfreearcdecoder.cpp \
    $$PWD/xrziparchive.cpp \
    $$PWD/xchmarchive.cpp \
    $$PWD/xntfsarchive.cpp \
    $$PWD/games/xhog2.cpp \
    $$PWD/games/xpboarchive.cpp \
    $$PWD/Algos/xu3rzipdecoder.cpp \
    $$PWD/xvirtualdiskarchive.cpp \
    $$PWD/xancient.cpp \
    $$PWD/xlegacyencoded.cpp \
    $$PWD/xdearkarchive.cpp \
    $$PWD/xdskexp.cpp \
    $$PWD/xlibdskarchive.cpp \
    $$PWD/xadfarchive.cpp \
    $$PWD/xcompactproarchive.cpp \
    $$PWD/xdiskdoublerarchive.cpp \
    $$PWD/xfls.cpp \
    $$PWD/xpyinstallercarchive.cpp \
    $$PWD/xwisesfxarchive.cpp \
    $$PWD/xis3sfxarchive.cpp \
    $$PWD/xis14sfxarchive.cpp \
    $$PWD/xlegacystorearchive.cpp \
    $$PWD/xconcatziparchive.cpp \
    $$PWD/xdiskjugglerarchive.cpp \
    $$PWD/xapplesingle.cpp \
    $$PWD/x2img.cpp \
    $$PWD/xpyz.cpp \
    $$PWD/xlzxarchive.cpp \
    $$PWD/xmi10archive.cpp \
    $$PWD/xmacbinary.cpp \
    $$PWD/xresourcefork.cpp \
    $$PWD/xlbr.cpp \
    $$PWD/xrtpatch.cpp \
    $$PWD/xrncarchive.cpp \
    $$PWD/xarq.cpp \
    $$PWD/xnetwarepackedfile.cpp \
    $$PWD/xpovlablzh.cpp \
    $$PWD/xearefpack.cpp \
    $$PWD/xprintshopdeluxe.cpp \
    $$PWD/xfrontpagetheme.cpp \
    $$PWD/xsecondnature.cpp \
    $$PWD/xlzpis2.cpp \
    $$PWD/xfinereaderpack.cpp \
    $$PWD/xecmpacked.cpp \
    $$PWD/xgstpack.cpp \
    $$PWD/xnpack.cpp \
    $$PWD/xcorelltec.cpp \
    $$PWD/xirwinpac.cpp \
    $$PWD/xdtpacked.cpp \
    $$PWD/xgashuff.cpp \
    $$PWD/xpowerboardbbs.cpp \
    $$PWD/xsilmarils.cpp \
    $$PWD/xis7inx.cpp \
    $$PWD/xrawlzw15v.cpp \
    $$PWD/xlbrcobol.cpp \
    $$PWD/xlsz.cpp \
    $$PWD/xgob.cpp \
    $$PWD/xgtu.cpp \
    $$PWD/xnotetab.cpp \
    $$PWD/xizpack.cpp \
    $$PWD/xsolarispackage.cpp \
    $$PWD/xhlb.cpp \
    $$PWD/xrid.cpp \
    $$PWD/xrompaq.cpp \
    $$PWD/xfiz.cpp \
    $$PWD/xmiz.cpp \
    $$PWD/xibmspack.cpp \
    $$PWD/xea.cpp \
    $$PWD/xsls.cpp \
    $$PWD/xpcsecure.cpp \
    $$PWD/xpmdiskcopy.cpp \
    $$PWD/xmegatechvol.cpp \
    $$PWD/xigf1.cpp \
    $$PWD/xjetbbs.cpp \
    $$PWD/xmakeself.cpp \
    $$PWD/xfld.cpp \
    $$PWD/xglu.cpp \
    $$PWD/xjam.cpp \
    $$PWD/xfmc1.cpp \
    $$PWD/xsoftpaq2.cpp \
    $$PWD/xmarc.cpp \
    $$PWD/xstork.cpp \
    $$PWD/xseadata.cpp \
    $$PWD/xqnxbase.cpp \
    $$PWD/xgamos.cpp \
    $$PWD/xsos.cpp \
    $$PWD/xexesbookbuilder.cpp \
    $$PWD/xhuff.cpp \
    $$PWD/xlzhcxp.cpp \
    $$PWD/xkrml.cpp \
    $$PWD/xqip1.cpp \
    $$PWD/xquantum.cpp \
    $$PWD/xirixsa.cpp \
    $$PWD/xjm93.cpp \
    $$PWD/xnextstepdiskimage.cpp \
    $$PWD/xmva.cpp \
    $$PWD/xpkt.cpp \
    $$PWD/xhdcopy.cpp \
    $$PWD/xivt.cpp \
    $$PWD/xswag.cpp \
    $$PWD/xstylus.cpp \
    $$PWD/xsettlersft.cpp \
    $$PWD/xriversoft.cpp \
    $$PWD/xgksetup.cpp \
    $$PWD/xopc.cpp \
    $$PWD/xgob2.cpp \
    $$PWD/xsq.cpp \
    $$PWD/xis11.cpp \
    $$PWD/xrecognita.cpp \
    $$PWD/xinteduft.cpp \
    $$PWD/xpaperport.cpp \
    $$PWD/xealib.cpp \
    $$PWD/xnid.cpp \
    $$PWD/xhap.cpp \
    $$PWD/xexeebookcreator.cpp \
    $$PWD/xlzdiet.cpp \
    $$PWD/xqualitas.cpp \
    $$PWD/xlzv1.cpp \
    $$PWD/xsw.cpp \
    $$PWD/xsaf.cpp \
    $$PWD/xigf2.cpp \
    $$PWD/xrcf.cpp \
    $$PWD/xhfe.cpp \
    $$PWD/xrsvk.cpp \
    $$PWD/xhzl.cpp \
    $$PWD/xjbf.cpp \
    $$PWD/xjgpak.cpp \
    $$PWD/xpackit.cpp \
    $$PWD/xlofi.cpp \
    $$PWD/xsci.cpp \
    $$PWD/xagis.cpp \
    $$PWD/xmwavez.cpp \
    $$PWD/xmscompresssz.cpp \
    $$PWD/xkolibrikpack.cpp \
    $$PWD/xmathcadpacked.cpp \
    $$PWD/xpcommos2.cpp \
    $$PWD/xsolarisbootarchive.cpp \
    $$PWD/xinfogramespak.cpp \
    $$PWD/xibmzpak.cpp \
    $$PWD/xquarterdeckqp.cpp \
    $$PWD/xmaxisinstall.cpp \
    $$PWD/xswagpacket.cpp \
    $$PWD/xpalmdatabase.cpp \
    $$PWD/xnetwareinstallfile.cpp \
    $$PWD/xaixbff.cpp \
    $$PWD/xaldus.cpp \
    $$PWD/xampk.cpp \
    $$PWD/xaodos.cpp \
    $$PWD/xarcv2.cpp \
    $$PWD/xarcv4.cpp \
    $$PWD/xarpdp11.cpp \
    $$PWD/xartipack.cpp \
    $$PWD/xascend.cpp \
    $$PWD/xascendbackup.cpp \
    $$PWD/xasymetrix.cpp \
    $$PWD/xbinaryii.cpp \
    $$PWD/xbinshsfx.cpp \
    $$PWD/xbluebytelib.cpp \
    $$PWD/xboo.cpp \
    $$PWD/xborlandpack.cpp \
    $$PWD/xbsn.cpp \
    $$PWD/xbthpak.cpp \
    $$PWD/xbvrppac.cpp \
    $$PWD/xbzip1.cpp \
    $$PWD/xinstallanywhere.cpp \
    $$PWD/xpcinstall.cpp \
    $$PWD/xsqz.cpp \
    $$PWD/xseaarc.cpp \
    $$PWD/xexternalarchive.cpp \
    $$PWD/xfreearc.cpp \
    $$PWD/xzpaq.cpp \
    $$PWD/xbcm.cpp \
    $$PWD/xlpaq8.cpp \
    $$PWD/xpea.cpp \
    $$PWD/xarj.cpp \
    $$PWD/xace.cpp \
    $$PWD/xfilteredarchive.cpp \
    $$PWD/xcab.cpp \
    $$PWD/xcfbf.cpp \
    $$PWD/xcpio.cpp \
    $$PWD/games/xpak.cpp \
    $$PWD/games/xwad.cpp \
    $$PWD/games/xgrp.cpp \
    $$PWD/games/xgodotpck.cpp \
    $$PWD/games/xwbfsarchive.cpp \
    $$PWD/games/xrvzarchive.cpp \
    $$PWD/games/xhog.cpp \
    $$PWD/games/xwolfvswap.cpp \
    $$PWD/games/xwintermutedcp.cpp \
    $$PWD/games/xt64.cpp \
    $$PWD/games/xgamestorearchive_p.cpp \
    $$PWD/games/xckp.cpp \
    $$PWD/games/xedp.cpp \
    $$PWD/games/xmpq.cpp \
    $$PWD/games/xbigf.cpp \
    $$PWD/games/xparsecarchive.cpp \
    $$PWD/games/xpmm.cpp \
    $$PWD/xwarc.cpp \
    $$PWD/xmtree.cpp \
    $$PWD/xshar.cpp \
    $$PWD/xuu.cpp \
    $$PWD/xdeb.cpp \
    $$PWD/xudf.cpp \
    $$PWD/xwim.cpp \
    $$PWD/xrpm.cpp \
    $$PWD/xkwaj.cpp \
    $$PWD/xasar.cpp \
    $$PWD/xxar.cpp \
    $$PWD/xzoo.cpp \
    $$PWD/xstk.cpp \
    $$PWD/xlha.cpp \
    $$PWD/xsar.cpp \
    $$PWD/xarx.cpp \
    $$PWD/xrar.cpp \
    $$PWD/xsevenzip.cpp \
    $$PWD/xsquashfs.cpp \
    $$PWD/xtar_bzip2.cpp \
    $$PWD/xtar_lzip.cpp \
    $$PWD/xtar_lzma.cpp \
    $$PWD/xtar_lzop.cpp \
    $$PWD/xtar_xz.cpp \
    $$PWD/xtar_zstd.cpp \
    $$PWD/xtar_lz4.cpp \
    $$PWD/xszdd.cpp \
    $$PWD/xbzip2.cpp \
    $$PWD/xbrotli.cpp \
    $$PWD/xlzip.cpp \
    $$PWD/xxz.cpp \
    $$PWD/xzlib.cpp \
    $$PWD/xzstd.cpp \
    $$PWD/xlz4.cpp \
    $$PWD/xlz5.cpp \
    $$PWD/xlizard.cpp \
    $$PWD/xlzma.cpp \
    $$PWD/xlzo.cpp \
    $$PWD/xcompressz.cpp \
    $$PWD/xminidump.cpp \
    $$PWD/xdmg.cpp

DISTFILES += \
    $$PWD/LICENSE \
    $$PWD/README.md \
    $$PWD/xarchive.cmake
