include_directories(${CMAKE_CURRENT_LIST_DIR})
include_directories(${CMAKE_CURRENT_LIST_DIR}/Algos/)
# The 7-Zip C public headers (LzmaDec.h, Ppmd7.h, 7zTypes.h, ...) live in
# Algos/include, kept apart from the first-party and generated sources.
# Consumers outside XArchive -- XStaticUnpacker's xnsis.cpp and xmew.cpp
# include LzmaDec.h -- resolve them from here without the vendored tree.
include_directories(${CMAKE_CURRENT_LIST_DIR}/Algos/include/)
# bzip2 headers (bzlib.h) moved to Algos/include with its sources; that path
# is already on the include list above.
# zlib headers moved to Algos/include with its sources; that path is already
# on the include list above.

# The shared core (all classes relocated to Formats, XCompress/XDecompress,
# ALL Algos decoders, and xbinary/xoptions) lives in xzip.cmake so it can be
# used WITHOUT the USE_ARCHIVE define; this file adds only the formats that
# remain in XArchive.
if (NOT DEFINED XZIP_SOURCES)
    include(${CMAKE_CURRENT_LIST_DIR}/xzip.cmake)
    set(XARCHIVE_SOURCES ${XARCHIVE_SOURCES} ${XZIP_SOURCES})
endif()

include("${CMAKE_CURRENT_LIST_DIR}/deark.cmake")
set(XARCHIVE_SOURCES ${XARCHIVE_SOURCES} ${XARCHIVE_DEARK_SOURCES})
include("${CMAKE_CURRENT_LIST_DIR}/legacydisk.cmake")
set(XARCHIVE_SOURCES ${XARCHIVE_SOURCES} ${XARCHIVE_LEGACYDISK_SOURCES})

set(XARCHIVE_SOURCES
    ${XARCHIVE_SOURCES}
    ${CMAKE_CURRENT_LIST_DIR}/x_ar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/x_ar.h
    ${CMAKE_CURRENT_LIST_DIR}/xsqlitearchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsqlitearchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xcpmcompressedarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcpmcompressedarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xu3cpmdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xu3cpmdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/xgitobjectarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgitobjectarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xalzarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xalzarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xfreearcnative.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfreearcnative.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xfreearcdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xfreearcdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/xrziparchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xchmarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xntfsarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xhog2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xpboarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrziparchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xchmarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xntfsarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xhog2.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xpboarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xu3rzipdecoder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/Algos/xu3rzipdecoder.h
    ${CMAKE_CURRENT_LIST_DIR}/xvirtualdiskarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xvirtualdiskarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xancient.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xancient.h
    ${CMAKE_CURRENT_LIST_DIR}/xlegacyencoded.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlegacyencoded.h
    ${CMAKE_CURRENT_LIST_DIR}/xdearkarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdearkarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xdskexp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdskexp.h
    ${CMAKE_CURRENT_LIST_DIR}/xlibdskarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlibdskarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xadfarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xadfarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xcompactproarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcompactproarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xdiskdoublerarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdiskdoublerarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xfls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfls.h
    ${CMAKE_CURRENT_LIST_DIR}/xpyinstallercarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpyinstallercarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xwisesfxarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xwisesfxarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xis3sfxarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xis3sfxarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xis14sfxarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xis14sfxarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xlegacystorearchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlegacystorearchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xconcatziparchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xconcatziparchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xdiskjugglerarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdiskjugglerarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xapplesingle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xapplesingle.h
    ${CMAKE_CURRENT_LIST_DIR}/x2img.cpp
    ${CMAKE_CURRENT_LIST_DIR}/x2img.h
    ${CMAKE_CURRENT_LIST_DIR}/xpyz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpyz.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzxarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzxarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xmi10archive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmi10archive.h
    ${CMAKE_CURRENT_LIST_DIR}/xmacbinary.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmacbinary.h
    ${CMAKE_CURRENT_LIST_DIR}/xresourcefork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xresourcefork.h
    ${CMAKE_CURRENT_LIST_DIR}/xlbr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlbr.h
    ${CMAKE_CURRENT_LIST_DIR}/xrtpatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrtpatch.h
    ${CMAKE_CURRENT_LIST_DIR}/xrncarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrncarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xarq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarq.h
    ${CMAKE_CURRENT_LIST_DIR}/xnetwarepackedfile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpovlablzh.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xearefpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xprintshopdeluxe.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfrontpagetheme.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsecondnature.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzpis2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfinereaderpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xecmpacked.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgstpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xnpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcorelltec.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xirwinpac.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdtpacked.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgashuff.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpowerboardbbs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsilmarils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xis7inx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrawlzw15v.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlbrcobol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlsz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgob.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgtu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xnotetab.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xizpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsolarispackage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xhlb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrompaq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfiz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmiz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xibmspack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xea.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsls.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpcsecure.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpmdiskcopy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmegatechvol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xigf1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xjetbbs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmakeself.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfld.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xglu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xjam.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfmc1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsoftpaq2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmarc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xstork.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xseadata.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xqnxbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgamos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xexesbookbuilder.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xhuff.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzhcxp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xkrml.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xqip1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xquantum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xirixsa.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xjm93.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xnextstepdiskimage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmva.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpkt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xhdcopy.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xivt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xswag.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xstylus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsettlersft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xriversoft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgksetup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xopc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xgob2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xis11.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrecognita.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xinteduft.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpaperport.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xealib.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xnid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xhap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xexeebookcreator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzdiet.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xqualitas.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzv1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsaf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xigf2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrcf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xhfe.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrsvk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xhzl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xjbf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xjgpak.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpackit.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlofi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsci.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xagis.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmwavez.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmscompresssz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xkolibrikpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmathcadpacked.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpcommos2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsolarisbootarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xinfogramespak.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xibmzpak.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xquarterdeckqp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmaxisinstall.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xswagpacket.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpalmdatabase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xnetwareinstallfile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xaixbff.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xaldus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xampk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xaodos.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarcv2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarcv4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarpdp11.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xartipack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xascend.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xascendbackup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xasymetrix.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbinaryii.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbinshsfx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbluebytelib.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xboo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xborlandpack.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbsn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbthpak.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbvrppac.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbzip1.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xinstallanywhere.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpcinstall.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xnetwarepackedfile.h
    ${CMAKE_CURRENT_LIST_DIR}/xpovlablzh.h
    ${CMAKE_CURRENT_LIST_DIR}/xearefpack.h
    ${CMAKE_CURRENT_LIST_DIR}/xprintshopdeluxe.h
    ${CMAKE_CURRENT_LIST_DIR}/xfrontpagetheme.h
    ${CMAKE_CURRENT_LIST_DIR}/xsecondnature.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzpis2.h
    ${CMAKE_CURRENT_LIST_DIR}/xfinereaderpack.h
    ${CMAKE_CURRENT_LIST_DIR}/xecmpacked.h
    ${CMAKE_CURRENT_LIST_DIR}/xgstpack.h
    ${CMAKE_CURRENT_LIST_DIR}/xnpack.h
    ${CMAKE_CURRENT_LIST_DIR}/xcorelltec.h
    ${CMAKE_CURRENT_LIST_DIR}/xirwinpac.h
    ${CMAKE_CURRENT_LIST_DIR}/xdtpacked.h
    ${CMAKE_CURRENT_LIST_DIR}/xgashuff.h
    ${CMAKE_CURRENT_LIST_DIR}/xpowerboardbbs.h
    ${CMAKE_CURRENT_LIST_DIR}/xsilmarils.h
    ${CMAKE_CURRENT_LIST_DIR}/xis7inx.h
    ${CMAKE_CURRENT_LIST_DIR}/xrawlzw15v.h
    ${CMAKE_CURRENT_LIST_DIR}/xlbrcobol.h
    ${CMAKE_CURRENT_LIST_DIR}/xlsz.h
    ${CMAKE_CURRENT_LIST_DIR}/xgob.h
    ${CMAKE_CURRENT_LIST_DIR}/xgtu.h
    ${CMAKE_CURRENT_LIST_DIR}/xnotetab.h
    ${CMAKE_CURRENT_LIST_DIR}/xizpack.h
    ${CMAKE_CURRENT_LIST_DIR}/xsolarispackage.h
    ${CMAKE_CURRENT_LIST_DIR}/xhlb.h
    ${CMAKE_CURRENT_LIST_DIR}/xrid.h
    ${CMAKE_CURRENT_LIST_DIR}/xrompaq.h
    ${CMAKE_CURRENT_LIST_DIR}/xfiz.h
    ${CMAKE_CURRENT_LIST_DIR}/xmiz.h
    ${CMAKE_CURRENT_LIST_DIR}/xibmspack.h
    ${CMAKE_CURRENT_LIST_DIR}/xea.h
    ${CMAKE_CURRENT_LIST_DIR}/xsls.h
    ${CMAKE_CURRENT_LIST_DIR}/xpcsecure.h
    ${CMAKE_CURRENT_LIST_DIR}/xpmdiskcopy.h
    ${CMAKE_CURRENT_LIST_DIR}/xmegatechvol.h
    ${CMAKE_CURRENT_LIST_DIR}/xigf1.h
    ${CMAKE_CURRENT_LIST_DIR}/xjetbbs.h
    ${CMAKE_CURRENT_LIST_DIR}/xmakeself.h
    ${CMAKE_CURRENT_LIST_DIR}/xfld.h
    ${CMAKE_CURRENT_LIST_DIR}/xglu.h
    ${CMAKE_CURRENT_LIST_DIR}/xjam.h
    ${CMAKE_CURRENT_LIST_DIR}/xfmc1.h
    ${CMAKE_CURRENT_LIST_DIR}/xsoftpaq2.h
    ${CMAKE_CURRENT_LIST_DIR}/xmarc.h
    ${CMAKE_CURRENT_LIST_DIR}/xstork.h
    ${CMAKE_CURRENT_LIST_DIR}/xseadata.h
    ${CMAKE_CURRENT_LIST_DIR}/xqnxbase.h
    ${CMAKE_CURRENT_LIST_DIR}/xgamos.h
    ${CMAKE_CURRENT_LIST_DIR}/xsos.h
    ${CMAKE_CURRENT_LIST_DIR}/xexesbookbuilder.h
    ${CMAKE_CURRENT_LIST_DIR}/xhuff.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzhcxp.h
    ${CMAKE_CURRENT_LIST_DIR}/xkrml.h
    ${CMAKE_CURRENT_LIST_DIR}/xqip1.h
    ${CMAKE_CURRENT_LIST_DIR}/xquantum.h
    ${CMAKE_CURRENT_LIST_DIR}/xirixsa.h
    ${CMAKE_CURRENT_LIST_DIR}/xjm93.h
    ${CMAKE_CURRENT_LIST_DIR}/xnextstepdiskimage.h
    ${CMAKE_CURRENT_LIST_DIR}/xmva.h
    ${CMAKE_CURRENT_LIST_DIR}/xpkt.h
    ${CMAKE_CURRENT_LIST_DIR}/xhdcopy.h
    ${CMAKE_CURRENT_LIST_DIR}/xivt.h
    ${CMAKE_CURRENT_LIST_DIR}/xswag.h
    ${CMAKE_CURRENT_LIST_DIR}/xstylus.h
    ${CMAKE_CURRENT_LIST_DIR}/xsettlersft.h
    ${CMAKE_CURRENT_LIST_DIR}/xriversoft.h
    ${CMAKE_CURRENT_LIST_DIR}/xgksetup.h
    ${CMAKE_CURRENT_LIST_DIR}/xopc.h
    ${CMAKE_CURRENT_LIST_DIR}/xgob2.h
    ${CMAKE_CURRENT_LIST_DIR}/xsq.h
    ${CMAKE_CURRENT_LIST_DIR}/xis11.h
    ${CMAKE_CURRENT_LIST_DIR}/xrecognita.h
    ${CMAKE_CURRENT_LIST_DIR}/xinteduft.h
    ${CMAKE_CURRENT_LIST_DIR}/xpaperport.h
    ${CMAKE_CURRENT_LIST_DIR}/xealib.h
    ${CMAKE_CURRENT_LIST_DIR}/xnid.h
    ${CMAKE_CURRENT_LIST_DIR}/xhap.h
    ${CMAKE_CURRENT_LIST_DIR}/xexeebookcreator.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzdiet.h
    ${CMAKE_CURRENT_LIST_DIR}/xqualitas.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzv1.h
    ${CMAKE_CURRENT_LIST_DIR}/xsw.h
    ${CMAKE_CURRENT_LIST_DIR}/xsaf.h
    ${CMAKE_CURRENT_LIST_DIR}/xigf2.h
    ${CMAKE_CURRENT_LIST_DIR}/xrcf.h
    ${CMAKE_CURRENT_LIST_DIR}/xhfe.h
    ${CMAKE_CURRENT_LIST_DIR}/xrsvk.h
    ${CMAKE_CURRENT_LIST_DIR}/xhzl.h
    ${CMAKE_CURRENT_LIST_DIR}/xjbf.h
    ${CMAKE_CURRENT_LIST_DIR}/xjgpak.h
    ${CMAKE_CURRENT_LIST_DIR}/xpackit.h
    ${CMAKE_CURRENT_LIST_DIR}/xlofi.h
    ${CMAKE_CURRENT_LIST_DIR}/xsci.h
    ${CMAKE_CURRENT_LIST_DIR}/xagis.h
    ${CMAKE_CURRENT_LIST_DIR}/xmwavez.h
    ${CMAKE_CURRENT_LIST_DIR}/xmscompresssz.h
    ${CMAKE_CURRENT_LIST_DIR}/xkolibrikpack.h
    ${CMAKE_CURRENT_LIST_DIR}/xmathcadpacked.h
    ${CMAKE_CURRENT_LIST_DIR}/xpcommos2.h
    ${CMAKE_CURRENT_LIST_DIR}/xsolarisbootarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xinfogramespak.h
    ${CMAKE_CURRENT_LIST_DIR}/xibmzpak.h
    ${CMAKE_CURRENT_LIST_DIR}/xquarterdeckqp.h
    ${CMAKE_CURRENT_LIST_DIR}/xmaxisinstall.h
    ${CMAKE_CURRENT_LIST_DIR}/xswagpacket.h
    ${CMAKE_CURRENT_LIST_DIR}/xpalmdatabase.h
    ${CMAKE_CURRENT_LIST_DIR}/xnetwareinstallfile.h
    ${CMAKE_CURRENT_LIST_DIR}/xaixbff.h
    ${CMAKE_CURRENT_LIST_DIR}/xaldus.h
    ${CMAKE_CURRENT_LIST_DIR}/xampk.h
    ${CMAKE_CURRENT_LIST_DIR}/xaodos.h
    ${CMAKE_CURRENT_LIST_DIR}/xarcv2.h
    ${CMAKE_CURRENT_LIST_DIR}/xarcv4.h
    ${CMAKE_CURRENT_LIST_DIR}/xarpdp11.h
    ${CMAKE_CURRENT_LIST_DIR}/xartipack.h
    ${CMAKE_CURRENT_LIST_DIR}/xascend.h
    ${CMAKE_CURRENT_LIST_DIR}/xascendbackup.h
    ${CMAKE_CURRENT_LIST_DIR}/xasymetrix.h
    ${CMAKE_CURRENT_LIST_DIR}/xbinaryii.h
    ${CMAKE_CURRENT_LIST_DIR}/xbinshsfx.h
    ${CMAKE_CURRENT_LIST_DIR}/xbluebytelib.h
    ${CMAKE_CURRENT_LIST_DIR}/xboo.h
    ${CMAKE_CURRENT_LIST_DIR}/xborlandpack.h
    ${CMAKE_CURRENT_LIST_DIR}/xbsn.h
    ${CMAKE_CURRENT_LIST_DIR}/xbthpak.h
    ${CMAKE_CURRENT_LIST_DIR}/xbvrppac.h
    ${CMAKE_CURRENT_LIST_DIR}/xbzip1.h
    ${CMAKE_CURRENT_LIST_DIR}/xinstallanywhere.h
    ${CMAKE_CURRENT_LIST_DIR}/xpcinstall.h
    ${CMAKE_CURRENT_LIST_DIR}/xsqz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsqz.h
    ${CMAKE_CURRENT_LIST_DIR}/xseaarc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xseaarc.h
    ${CMAKE_CURRENT_LIST_DIR}/xexternalarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xexternalarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xfreearc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfreearc.h
    ${CMAKE_CURRENT_LIST_DIR}/xzpaq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xzpaq.h
    ${CMAKE_CURRENT_LIST_DIR}/xbcm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbcm.h
    ${CMAKE_CURRENT_LIST_DIR}/xlpaq8.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlpaq8.h
    ${CMAKE_CURRENT_LIST_DIR}/xpea.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xpea.h
    ${CMAKE_CURRENT_LIST_DIR}/xarj.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarj.h
    ${CMAKE_CURRENT_LIST_DIR}/xace.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xace.h
    ${CMAKE_CURRENT_LIST_DIR}/xfilteredarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xfilteredarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/xcab.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcab.h
    ${CMAKE_CURRENT_LIST_DIR}/xcfbf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcfbf.h
    ${CMAKE_CURRENT_LIST_DIR}/xcpio.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcpio.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xpak.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xpak.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xwad.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xwad.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xgrp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xgrp.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xgodotpck.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xgodotpck.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xwbfsarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xwbfsarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xrvzarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xrvzarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xhog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xhog.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xwolfvswap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xwolfvswap.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xwintermutedcp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xwintermutedcp.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xt64.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xt64.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xgamestorearchive_p.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xgamestorearchive_p.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xckp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xckp.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xedp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xedp.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xmpq.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xmpq.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xbigf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xbigf.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xparsecarchive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xparsecarchive.h
    ${CMAKE_CURRENT_LIST_DIR}/games/xpmm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/games/xpmm.h
    ${CMAKE_CURRENT_LIST_DIR}/xwarc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xwarc.h
    ${CMAKE_CURRENT_LIST_DIR}/xmtree.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xmtree.h
    ${CMAKE_CURRENT_LIST_DIR}/xshar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xshar.h
    ${CMAKE_CURRENT_LIST_DIR}/xuu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xuu.h
    ${CMAKE_CURRENT_LIST_DIR}/xdeb.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdeb.h
    ${CMAKE_CURRENT_LIST_DIR}/xudf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xudf.h
    ${CMAKE_CURRENT_LIST_DIR}/xwim.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xwim.h
    ${CMAKE_CURRENT_LIST_DIR}/xrpm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrpm.h
    ${CMAKE_CURRENT_LIST_DIR}/xkwaj.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xkwaj.h
    ${CMAKE_CURRENT_LIST_DIR}/xasar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xasar.h
    ${CMAKE_CURRENT_LIST_DIR}/xxar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xxar.h
    ${CMAKE_CURRENT_LIST_DIR}/xzoo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xzoo.h
    ${CMAKE_CURRENT_LIST_DIR}/xstk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xstk.h
    ${CMAKE_CURRENT_LIST_DIR}/xlha.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsar.h
    ${CMAKE_CURRENT_LIST_DIR}/xarx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xarx.h
    ${CMAKE_CURRENT_LIST_DIR}/xlha.h
    ${CMAKE_CURRENT_LIST_DIR}/xrar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrar.h
    ${CMAKE_CURRENT_LIST_DIR}/xsevenzip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsevenzip.h
    ${CMAKE_CURRENT_LIST_DIR}/xsquashfs.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xsquashfs.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_bzip2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_bzip2.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzip.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzma.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzma.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lzop.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_xz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_xz.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_zstd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_zstd.h
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lz4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xtar_lz4.h
    ${CMAKE_CURRENT_LIST_DIR}/xzstd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xzstd.h
    ${CMAKE_CURRENT_LIST_DIR}/xlz4.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlz4.h
    ${CMAKE_CURRENT_LIST_DIR}/xlz5.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlz5.h
    ${CMAKE_CURRENT_LIST_DIR}/xlizard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlizard.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzma.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzma.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzo.h
    ${CMAKE_CURRENT_LIST_DIR}/xcompressz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xcompressz.h
    ${CMAKE_CURRENT_LIST_DIR}/xzlib.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xzlib.h
    ${CMAKE_CURRENT_LIST_DIR}/xszdd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xszdd.h
    ${CMAKE_CURRENT_LIST_DIR}/xbzip2.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbzip2.h
    ${CMAKE_CURRENT_LIST_DIR}/xbrotli.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xbrotli.h
    ${CMAKE_CURRENT_LIST_DIR}/xlzip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xlzip.h
    ${CMAKE_CURRENT_LIST_DIR}/xxz.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xxz.h
    ${CMAKE_CURRENT_LIST_DIR}/xminidump.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xminidump.h
    ${CMAKE_CURRENT_LIST_DIR}/xdmg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xdmg.h
)
