/* Copyright (c) 2026 hors<horsicq@gmail.com>
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#ifndef XHADECODER_H
#define XHADECODER_H

#include "../xbinary.h"

// HA method 2, "HSC" - an order-4 PPM with escape coding over a
// Witten-Neal-Cleary arithmetic coder with 16-bit registers.  Written from the
// reference decompressor (VA 0x004bb180 .. 0x004bcd20); no third-party code is
// vendored, which matters because HA's own sources are GPL and this tree is
// MIT.
//
// The shape, for anyone who has to touch it again:
//
//  * Contexts live in a fixed pool of 10000 nodes addressed by a 16384-entry
//    hash of the last 1..4 bytes.  The hash mixes through a table of 16384
//    values generated by a MINSTD (Schrage) generator seeded at 10 - the table
//    is NOT arbitrary, the decoder must reproduce it exactly.
//  * A context node doubles as the FIRST slot of its own symbol list; further
//    symbols come from a pool above index 10000 chained through the same
//    "next" array.  That is why context indices and symbol-slot indices share
//    one address space.
//  * Coding walks from the deepest matching context down, emitting an escape
//    per level and accumulating an exclusion set as it goes; a total miss
//    falls through to an order -1 model over the not-yet-excluded symbols.
//  * When the context pool is full the LEAST RECENTLY USED context is
//    recycled, and when the symbol pool is full a context that is not on the
//    current escape path has its rarest symbols merged away.  Both are part of
//    the bitstream contract, not housekeeping: get either wrong and the coder
//    desynchronises.
//  * After 2500 order-4 contexts have been recycled the model permanently
//    drops to order 3.
// HA method 1, "ASC" - LZ77 over a 31200-byte circular window, entropy coded
// with the same arithmetic coder.  Written from the reference decompressor
// (VA 0x004bd290 .. 0x004bd260) under the same no-vendoring rule as HSC.
//
// The shape:
//
//  * Five implicit binary cumulative-frequency trees (leaves at [n .. 2n-1],
//    running total at [1]): seen chars / not-yet-seen chars (256 codes each),
//    seen lengths / not-yet-seen lengths (64 each), and positions (16).
//  * A literal-or-match decision comes from a 4-state binary context built
//    from the last two decisions, with a dedicated end-of-stream slot one
//    above the two weights.
//  * Chars and lengths use a two-level "seen / not yet seen" escape model: a
//    miss in the seen tree escapes into the not-yet-seen tree, which then
//    loses that symbol and bumps its still-unseen NEIGHBOURS, so locality in
//    the alphabet is modelled.  The neighbourhood's upper bound is exclusive
//    in the decoder while HA's encoder is inclusive - a real asymmetry in the
//    original; do not "fix" it or the coder desynchronises.
//  * Positions are 16 buckets that go live as the output grows, bucket k
//    covering [2^(k-1), 2^k) with uniform extra bits, the top live bucket
//    clamped to the bytes actually produced so far.
//  * Length code 15 is reserved for the longest match (783 + MINLEN); codes
//    16..63 carry 4 extra bits each.
class XHADecoder {
public:
    static bool decodeHSC(const QByteArray &baPacked, qint64 nUncompressedSize, QByteArray *pbaResult, XBinary::PDSTRUCT *pPdStruct = nullptr);
    static bool decodeASC(const QByteArray &baPacked, qint64 nUncompressedSize, QByteArray *pbaResult, XBinary::PDSTRUCT *pPdStruct = nullptr);
};

#endif  // XHADECODER_H
